#!/usr/bin/env bash
# I havent used fd bcoz if it is not  pre installed we get isssue hence i avoided
echo "Removed binary files "
find . -maxdepth 1 -type f \( -name "*.out" -o -name "*.o" -o -executable \) -delete -print
