#!/usr/bin/env bash
 find . -name .git -type d -prune | while read -r gitdir; do
    root_repository="$(dirname "$gitdir")"
    echo "clean repo that ignored in  git : $root_repository"
    (cd "$root_repository" && git clean -Xdf)

done